version: "3"

volumes:
  loki_data: {}
  grafana_data: {}

networks:
  cloudflare-tunnel: {}
  logging:
    name: logging

services:
  website:
    container_name: website
    image: vocksel/vocksel.com:main
    restart: unless-stopped
    ports:
      - "8080:3000"
    networks:
      - cloudflare-tunnel
      - logging
    logging:
      driver: "loki"
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"

  swatch:
    container_name: swatch
    image: vocksel/swatch:main
    restart: unless-stopped
    ports:
      - "8100:8080"
    networks:
      - cloudflare-tunnel
      - logging
    logging:
      driver: "loki"
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"

  loki:
    container_name: loki
    image: grafana/loki:2.9.4
    ports:
      - "3100:3100"
    volumes:
      - ./loki.yml:/etc/loki-config.yml
      - loki_data:/loki
    command: -config.file=/etc/loki-config.yml
    networks:
      - logging

  promtail:
    container_name: promtail
    image: grafana/promtail:2.9.4
    volumes:
      - ./promtail.yml:/etc/promtail/config.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_logs:/var/log/caddy:ro
    command: -config.file=/etc/promtail/config.yml
    networks:
      - logging

  grafana:
    container_name: grafana
    image: grafana/grafana:10.3.1
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yaml
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - cloudflare-tunnel
      - logging

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - cloudflare-tunnel
